version: "3"

services:
  nginx:
    depends_on:
      - "mbit"
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "static_volume:/app/staticfiles"
    container_name: nginx

  mbit:
    build: mbit-app/
    restart: always
    expose:
      - "8000"
    volumes:
      - "./mbit-app:/app:ro"
      - "static_volume:/app/staticfiles"
    env_file:
      - "./env/env.prod"
    container_name: mbit
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"      
    env_file:
      - "./env/env.prod.db"
    container_name: postgres

volumes:
  static_volume:
  postgres_data: