version: "3"

services:
  mbit:
    build: mbit-app/
    restart: always
    expose:
      - "8000"
    volumes:
      - "./mbit-app:/app:ro"
      - "static_volume:/app/staticfiles"
    env_file:
      - "./env/env.prod"
    container_name: mbit
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"      
    env_file:
      - "./env/env.prod.db"

volumes:
  static_volume: