version: "3"

services:
  mbit:
    build: mbit-app/
    restart: always
    expose:
      - "8000"
    volumes:
      - "./mbit-app:/app:ro"
      - "static_volume:/app/"
    container_name: mbit
  
volumes:
  static_volume: