name: Build to EB
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    name: Build EB
    runs-on: ubuntu-latest
    steps:
      - name: "1. Github repostory 체크아웃"
        uses: actions/checkout@v2
      
      - name: "2. 시간대 맞추기"
        uses: 1466587594/get-current-time@v2 
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"   
      
      - name: "3. 도커이미지 빌드"
        run: |
          docker build --tag yshrim12/django-mbit ./MBIT-app
          docker build --tag yshrim12/mbit-nginx ./nginx
      
      - name: "4. 도커허브 로그인"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username:  ${{ secrets.DOCKER_USERNAME }} 
          password:  ${{ secrets.DOCKER_PASSWORD }} 
      
      - name: "5. 도커허브로 이미지 푸시"
        run: |
          docker push yshrim12/django-mbit
          docker push yshrim12/mbit-nginx

      - name: "6. make zip file"
        run: |
          mkdir -p deploy
          cp -R env MBIT-app nginx docker-compose.yml init-letsencrypt.sh deploy/
          cd deploy && zip -r deploy.zip .
      
      - name: "6-1 Check zip file"
        run: |
          pwd && ls -lh
          unzip -l deploy/deploy.zip
      
      # - name: "7. Deploy to EB"
      # uses: einaregilsson/beanstalk-deploy@v20
      # with:
      #   aws_access_key:  ${{ secrets.AWS_ACCESS_KEY }} 
      #   aws_secret_key:  ${{ secrets.AWS_SECRET_KEY }} 
      #   application_name: aws-eb-mbit     # 엘라스틱 빈스톡 애플리케이션 이름!
      #   environment_name: Aws-eb-mbit-env # 엘라스틱 빈스톡 환경 이름!
      #   version_label:  github-action-${{ steps.current-time.outputs.formattedTime }} 
      #   region: ap-northeast-2
      #   deployment_package: deploy/deploy.zip